---
- hosts: localhost
  tasks:
  # - name: install the latest version of git
  #   yum:
  #     name: git
  #     state: latest

  - name: Adding epel repository
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

  - name: install multple apps
    yum:
      name: "{{ item }}"
      state: latest
    loop:
     - nginx
